kind: Deployment
apiVersion: apps/v1
metadata:
  name: fastapi-app
  namespace: fastapi
  labels:
    app: fastapi-app
    app.kubernetes.io/component: fastapi-app
    app.kubernetes.io/instance: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: fastapi-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: fastapi-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: fastapi-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/team1-app/fastapi:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
