apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fastapi
  namespace: team1-app
  labels:
    app: fastapi
    app.kubernetes.io/component: fastapi
spec:
  to:
    kind: Service
    name: fastapi-service
  port:
    targetPort: 8080
