apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: team1-app
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
